name: Python CI

# Runs on pushes and pull requests to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Full pytest test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pip install pytest
        pytest
  
  Partial pytest test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check for changes in 'tests' folder
        id: check_new_tests
        run: |
          if git diff origin/main | grep -q "^tests/"; then
            echo "tests folder changed"
            echo "RUN_TESTS=true" >> $GITHUB_ENV
          else
            echo "tests folder not changed"
            echo "RUN_TESTS=false" >> $GITHUB_ENV
          fi

    - name: Run tests
      if: env.RUN_TESTS == 'true'
      run: |
        pip install pytest
        pytest 

